config/routes.rb
Rails.application.routes.draw do
  
  post  'admins/signin'
  resources :transactions
  resources :banks
  resources :admins
  resources :citizens
        
      get 'citizen/list'
      get 'citizen/new'
      post 'citizen/create'
      post 'citizen/new'
      post 'transactions/create'  
      root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/destroy' => 'sessions#destroy'

end

app/models/citizen.rb
class Citizen < ActiveRecord::Base
	has_many :accounts
	has_many :banks, through: :accounts
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  before_action :set_citizen, only: [:show, :edit, :update, :destroy]

  # GET /citizens
  # GET /citizens.json
  def index
    @citizens = Citizen.all
  end

  # GET /citizens/1
  # GET /citizens/1.json
  def show
  end

  # GET /citizens/new
  def new
    @citizen = Citizen.new
  end

  # GET /citizens/1/edit
  def edit
  end

  # POST /citizens
  # POST /citizens.json
  def create
    @citizen = Citizen.new(citizen_params)

    respond_to do |format|
      if @citizen.save
        format.html { redirect_to @citizen, notice: 'Citizen was successfully created.' }
        format.json { render :show, status: :created, location: @citizen }
      else
        format.html { render :new }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citizens/1
  # PATCH/PUT /citizens/1.json
  def update
    respond_to do |format|
      if @citizen.update(citizen_params)
        format.html { redirect_to @citizen, notice: 'Citizen was successfully updated.' }
        format.json { render :show, status: :ok, location: @citizen }
      else
        format.html { render :edit }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citizens/1
  # DELETE /citizens/1.json
  def destroy
    @citizen.destroy
    respond_to do |format|
      format.html { redirect_to citizens_url, notice: 'Citizen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citizen
      @citizen = Citizen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def citizen_params
      params.require(:citizen).permit(:name, :phone_num1, :phone_num2, :email, :address, :nat_id)
    end
end

app/helpers/citizen_helper.rb
module CitizenHelper
end

app/views/citizens/_form.html.erb
<%= form_for(@citizen) do |f| %>
  <% if @citizen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@citizen.errors.count, "error") %> prohibited this citizen from being saved:</h2>

      <ul>
      <% @citizen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_num1 %><br>
    <%= f.text_field :phone_num1 %>
  </div>
  <div class="field">
    <%= f.label :phone_num2 %><br>
    <%= f.text_field :phone_num2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :nat_id %><br>
    <%= f.text_field :nat_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citizens/edit.html.erb
<h1>Editing Citizen</h1>

<%= render 'form' %>

<%= link_to 'Show', @citizen %> |
<%= link_to 'Back', citizens_path %>

app/views/citizens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Citizens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone num1</th>
      <th>Phone num2</th>
      <th>Email</th>
      <th>Address</th>
      <th>Nat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @citizens.each do |citizen| %>
      <tr>
        <td><%= citizen.name %></td>
        <td><%= citizen.phone_num1 %></td>
        <td><%= citizen.phone_num2 %></td>
        <td><%= citizen.email %></td>
        <td><%= citizen.address %></td>
        <td><%= citizen.nat_id %></td>
        <td><%= link_to 'Show', citizen %></td>
        <td><%= link_to 'Edit', edit_citizen_path(citizen) %></td>
        <td><%= link_to 'Destroy', citizen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Citizen', new_citizen_path %>

app/views/citizens/new.html.erb
<h1>New Citizen</h1>

<%= render 'form' %>

<%= link_to 'Back', citizens_path %>

app/views/citizens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @citizen.name %>
</p>

<p>
  <strong>Phone num1:</strong>
  <%= @citizen.phone_num1 %>
</p>

<p>
  <strong>Phone num2:</strong>
  <%= @citizen.phone_num2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @citizen.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @citizen.address %>
</p>

<p>
  <strong>Nat:</strong>
  <%= @citizen.nat_id %>
</p>

<%= link_to 'Edit', edit_citizen_path(@citizen) %> |
<%= link_to 'Back', citizens_path %>