config/routes.rb
Rails.application.routes.draw do
  
  post  'admins/signin'
  resources :transactions
  resources :banks
  resources :admins
  resources :citizens
        
      get 'citizen/list'
      get 'citizen/new'
      post 'citizen/create'
      post 'citizen/new'
      post 'transactions/create'  
      root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/destroy' => 'sessions#destroy'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :accounts
	has_many :customers, class_name: 'Citizen', through: :accounts
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
    render json: @banks
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, :type, :reg_no, :founded, :headquarters, :ceo, :services, :email, :website, :logo_url)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :reg_no %><br>
    <%= f.text_field :reg_no %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.date_select :founded %>
  </div>
  <div class="field">
    <%= f.label :headquarters %><br>
    <%= f.text_field :headquarters %>
  </div>
  <div class="field">
    <%= f.label :ceo %><br>
    <%= f.text_field :ceo %>
  </div>
  <div class="field">
    <%= f.label :services %><br>
    <%= f.text_field :services %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Banks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Reg no</th>
      <th>Founded</th>
      <th>Headquarters</th>
      <th>Ceo</th>
      <th>Services</th>
      <th>Email</th>
      <th>Website</th>
      <th>Logo url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= bank.bank_type %></td>
        <td><%= bank.reg_no %></td>
        <td><%= bank.founded %></td>
        <td><%= bank.headquarters %></td>
        <td><%= bank.ceo %></td>
        <td><%= bank.services %></td>
        <td><%= bank.email %></td>
        <td><%= bank.website %></td>
        <td><%= bank.logo_url %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New Bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bank.type %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @bank.reg_no %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @bank.founded %>
</p>

<p>
  <strong>Headquarters:</strong>
  <%= @bank.headquarters %>
</p>

<p>
  <strong>Ceo:</strong>
  <%= @bank.ceo %>
</p>

<p>
  <strong>Services:</strong>
  <%= @bank.services %>
</p>

<p>
  <strong>Email:</strong>
  <%= @bank.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @bank.website %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @bank.logo_url %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>